version: '3'
services:
    web:
      build: .
      command: npm run dev
      volumes:
        - .:/SaisieAbs/
        - /SaisieAbs/node_modules
      ports:
        - "3000:3000"
      depends_on:
        - mysql
    mysql:
      image: mysql:8
      environment:
        MYSQL_USER: root
        MYSQL_DB: tp